Repository red-hat-storage/ceph-csi-operator, pull requests merged in 2025-09, with the labels that each got.

#101 bundle: add priorityClassName to csv deployments
  Makefile.Downstream.mk
  bundle/manifests/cephcsi-operator.clusterserviceversion.yaml
  config/manager/manager_priority_class_patch.yaml
  hack/update-csv-timestamp.sh
Labels: lgtm, approved

#146 DFBUGS-3992: [release-4.20] rbac: include the role and rolebinding for CephFS nodeplugin
  bundle/manifests/cephcsi-operator.clusterserviceversion.yaml
  config/csi-rbac/kustomization.yaml
  deploy/all-in-one/install.yaml
  deploy/charts/ceph-csi-drivers/templates/cephfs-nodeplugin-r-rbac.yaml
  deploy/charts/ceph-csi-drivers/templates/cephfs-nodeplugin-rb-rbac.yaml
  deploy/charts/ceph-csi-operator/templates/cephfs-nodeplugin-r-rbac.yaml
  deploy/charts/ceph-csi-operator/templates/cephfs-nodeplugin-rb-rbac.yaml
  deploy/multifile/csi-rbac.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, jira/severity-important

#141 [release-4.20]: csi: add snapshotmetadataservice crd existence check
  internal/controller/driver_controller.go
Labels: lgtm, approved, jira/valid-bug

#149 DFBUGS-4259: [release-4.20] deploy: Add watch permission for Secrets to CephFS ctrlplugin
  bundle/manifests/cephcsi-operator.clusterserviceversion.yaml
  config/csi-rbac/cephfs_ctrlplugin_cluster_role.yaml
  deploy/all-in-one/install.yaml
  deploy/charts/ceph-csi-drivers/templates/cephfs-ctrlplugin-cr-rbac.yaml
  deploy/charts/ceph-csi-operator/templates/cephfs-ctrlplugin-cr-rbac.yaml
  deploy/multifile/csi-rbac.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
